### ISSUE TITLE
Ermittlung aller Umsteigepunkte (Up) auf einer Linie

### ISSUE THREAD

**Issue by slempart** [andrekirst/04_KataFahrplanauskunft#38]
# Beschreibung:

Erstellen einer Funktion zur Ermittlung aller Umsteigepunkte (Up) auf einer Linie

## Betroffene Komponenten

* [x] Fahrplanauskunft
* [x] Fahrplanauskunft.Test

## Dokumentationsanpassungen

* [x] Beschreibungs-Dokumentationen
  * [x] Architektur-Handbuch
* [x] Testfall-Dokumentation
* [x] Release-Notes

## Testfälle

* [x] **Fahrplanauskunft**
  * [x] *Ermittlung der Umsteigepunkte einer Linie* - Liefere die Liste von Umsteigepunkte einer Linie

**Comment by andrekirst** [comment]
Ich habe die Testdaten nach develop gemerged.

**Comment by andrekirst** [comment]
Mit PR #50 umgesetzt. Kann geschlossen werden.
