### ISSUE TITLE
Fachliche Änderung des Begriffes Name und Ident bei Linie

### ISSUE THREAD

**Issue by slempart** [andrekirst/04_KataFahrplanauskunft#45]
# Beschreibung:

Der `Name` des Objektes `Linie` ist das gemeinsame Attribut für die Linienführung in der Hin- sowie der Gegenrichtung.
Der `Ident` ist das eindeutige Attribut für eine Richtung einer `Linie`.
Z.B.
Vorher:

| Name | Ident |
| --- | --- |
| B11 | B11_SUED |
| B12 | B12_NORD |

Nachher:

| Name | Ident |
| --- | --- |
| B1 | B11_SUED |
| B1 | B12_NORD |

## Betroffene Komponenten

* [x] Fahrplanauskunft
* [x] Fahrplanauskunft.Test

## Dokumentationsanpassungen

* [x] Beschreibungs-Dokumentationen
  * [x] [Objekt-Dokumentation](/andrekirst/04_KataFahrplanauskunft/blob/develop/Dokumentation/Objekte/Linie.md)
  * [x] [Test-Dokumentation](/andrekirst/04_KataFahrplanauskunft/blob/develop/Dokumentation/Tests/Objekte/Linie.md)
* [x] Testfall-Dokumentation
* [x] Release-Notes

## Testfälle

* [x] **Fahrplanauskunft**
  * [x] *Linie_Konstruktor_Name_Test_Ident_TEST* - Test, ob der Name den Wert "Test" beinhaltet und der Ident den Wert "TEST" beinhaltet.
  * [x] *Haltestelle_Equals_Name_Test_Ident_TEST* - Test der Equals-Methode, dass zwei Linien gleich sind. Name: "Test", Ident: "TEST"
  * [x] **Anpassung der Tests aufgrund der fachlichen Änderung**

**Comment by slempart** [comment]
Unklar, ob hier noch etwas gemacht werden muss, ich würde sagen es ist erstmal in Ordnung. Was meinst du @andrekirst?

**Comment by andrekirst** [comment]
@slempart Eigentlich muss hier nichts gemacht werden, weil die Änderungen bereits in #38 eingefügt (gemerged) wurden. Könnte man als eine der Konsequenzen daraus nehmen. Ich schließe den Issue und lösche den Branch auf GitHub. Musst ihn also auch lokal löschen
