### ISSUE TITLE
Nächste mögliche Umstiegspunkte

### ISSUE THREAD

**Issue by slempart** [andrekirst/04_KataFahrplanauskunft#53]
# Beschreibung:

Suche neue Umstiegspunkte von einer Haltestelle aus, aber ignoriere Umstiegspunkte bei denen man schon war

## Betroffene Komponenten

* [x] Fahrplanauskunft
* [x] Fahrplanauskunft.Test

## Dokumentationsanpassungen

* [x] Beschreibungs-Dokumentationen
  * [x] Architektur-Handbuch
* [x] Testfall-Dokumentation
* [x] Release-Notes

## Testfälle

* [x] **Fahrplanauskunft**
  * [x] *Ermittlung der nächste mögliche Umstiegspunkte* - *Liefere die nächsten möglichen Umstiegspunkte einer Haltestelle und ignoriere schon bereits ermittelte Umstiegspunkte*

**Comment by andrekirst** [comment]
Mit PR #54 umgesetzt. Kann geschlossen werden.
