### ISSUE TITLE
Liefere die hierarchische Struktur von möglichen Umstiegspunkten von einer Haltestelle

### ISSUE THREAD

**Issue by slempart** [andrekirst/04_KataFahrplanauskunft#56]
# Beschreibung:

Es soll die hierarchische Struktur von möglichen Umstiegspunkten von einer Haltestelle geliefert werden.  
Dabei ist der Einstiegspunkt(Wurzel) ein beliebige Haltestelle.  
Von der Haltestelle aus werden die nächsten möglichen Umstiegspunkte ermittelt, von den ermittelten Umstiegpunkten werden wieder die nächsten möglichen Umstiegspunkte ermittelt und so weiter.  
Die Ergebnisse werden in der hierarchische Struktur von Umstiegspunkten gespeichert.
Abbruchbedingung sind:  
 - Es gibt keine weitere Umstiegspunkte  
 - Es wird bis zu einer maximale Anzahl (hierarchischen Tiefe) von Umstiegspunkte  gesucht

## Betroffene Komponenten

* [x] Fahrplanauskunft
* [x] Fahrplanauskunft.Test

## Dokumentationsanpassungen

* [x] Beschreibungs-Dokumentationen
  * [x] Architektur-Handbuch
* [x] Testfall-Dokumentation
* [x] Release-Notes

## Testfälle

* [x] **Fahrplanauskunft**
  * [x] *Hierarchie-Objekt* - Für das Hierarchie-Objekt (TreeItem) soll die Equal-Methode getestet werden, dabei solle jeweils 3 Fälle mit 1, 2 sowie 3 Ebenen als positiv und negativ Test geschrieben werden.
  * [x] *Liefere die Hierarchie von Umstiegspunkten für eine Haltestelle* - Es soll die Hierarchie von Umstiegspunkten für 3 Fälle geliefert werden
  * [x] *Liefere die Hierarchie von Umstiegspunkten für eine Haltestelle mit einer Tiefe von 1* - Es soll die Hierarchie von Umstiegspunkten für 3 Fälle geliefert werden, wobei die Tiefe 1 sein soll

**Comment by andrekirst** [comment]
Mit PR #66 umgesetzt. Kann geschlossen werden.
