### ISSUE TITLE
ToString-Methode für Umstiegspunkt implementieren

### ISSUE THREAD

**Issue by slempart** [andrekirst/04_KataFahrplanauskunft#63]
# Beschreibung:

Es soll die ToString-Methode in der Klasse `Umstiegspunkt` überschrieben und implementiert werden. Ausgegeben werden soll z.B. "Name: H4"

## Betroffene Komponenten

* [x] Fahrplanauskunft
* [x] Fahrplanauskunft.Test

## Dokumentationsanpassungen

* [x] Testfall-Dokumentation
* [x] Release-Notes

## Testfälle

* [x] **Fahrplanauskunft.Test**
  * [x] *Umstiegspunkt_ToString* - Test, dass die Rückgabe **Name: H4** ist, wenn der Name des Umstiegspunkt**H4** ist.

**Comment by andrekirst** [comment]
Ist umgesetzt. Kann geschlossen werden.
