### ISSUE TITLE
Dokumentation als PDF oder HTML erzeugen und im Deployment einschließen

### ISSUE THREAD

**Issue by andrekirst** [andrekirst/04_KataFahrplanauskunft#92]
# Beschreibung

Die Dokumente sollen als PDF oder HTML-Ausgabe erzeugt werden und in den Deployment-Prozess eingebunden werden.

## Dokumentationsanpassungen
* [x] Deployment-Handbuch
* [x] Build-Prozess
* [x] Release-Notes

## Ablauf beim Entwickeln und Code Review

* [x] Branch erstellt
* [x] Dem Issue das Label `branch erstellt` vergeben
* [x] Entwicklungsarbeit
* [x] Pull Request erstellt
* [x] Dem Issue das Label `pr erstellt` vergeben
* [x] Der Pull Request-Ersteller behebt die von StyleCop und anderen Analyzern entstandenen Einträge
* [x] Der Pull Request-Ersteller behebt in der Entwicklung entstandene SonarQube-Einträge (Bugs, Vulnerabilities, Code Smells, Coverage, Duplications) *([https://sonarqube.com/dashboard/index/04_KataFahrplanauskunft](https://sonarqube.com/dashboard/index/04_KataFahrplanauskunft))*
* [x] Der Pull Request-Ersteller behebt in der Entwicklung entstandene Coveralls.io-Einträge (Code Coverage) *([https://coveralls.io/github/andrekirst/04_KataFahrplanauskunft](https://coveralls.io/github/andrekirst/04_KataFahrplanauskunft))*
* [x] Der Pull Request-Ersteller behebt die vom Code Reviewer bemängelten Stellen bzw. bespricht diese

**Comment by slempart** [comment]
Hat funktioniert

**Comment by andrekirst** [comment]
Mit PR #96 umgesetzt. Kann geschlossen werden.
