### ISSUE TITLE
Berechnung einer Verbindungsauskunft

### ISSUE THREAD

**Issue by andrekirst** [andrekirst/04_KataFahrplanauskunft#97]
# Beschreibung

Es sollen Verbindungsauskünfte berechnet werden, die eine Start- und Ziel-Haltestelle beinhalten, sowie die gewünschte Abfahrtszeit. Zurückgegeben werden sollen Verbindungsauskünfte mit 1. der niedrigsten Reisedauer, 2. der am nähesten zur gewünschten Abfahrtszeit und 3. die wenigsten Umstiege.

## Betroffene Komponenten

* [ ] Fahrplanauskunft
* [ ] Fahrplanauskunft.Test

## Dokumentationsanpassungen

* [ ] Testfall-Dokumentation
* [ ] Release-Notes

## Testfälle

* [ ] **Fahrplanauskunft.Test**
  * [ ] *Testfälle dokumentieren*

## Ablauf beim Entwickeln und Code Review

* [x] Branch erstellt
* [x] Dem Issue das Label `branch erstellt` vergeben
* [ ] Entwicklungsarbeit
* [ ] Pull Request erstellt
* [ ] Dem Issue das Label `pr erstellt` vergeben
* [ ] Der Pull Request-Ersteller behebt die von StyleCop und anderen Analyzern entstandenen Einträge
* [ ] Der Pull Request-Ersteller behebt in der Entwicklung entstandene SonarQube-Einträge (Bugs, Vulnerabilities, Code Smells, Coverage, Duplications) *([https://sonarqube.com/dashboard/index/04_KataFahrplanauskunft](https://sonarqube.com/dashboard/index/04_KataFahrplanauskunft))*
* [ ] Der Pull Request-Ersteller behebt in der Entwicklung entstandene Coveralls.io-Einträge (Code Coverage) *([https://coveralls.io/github/andrekirst/04_KataFahrplanauskunft](https://coveralls.io/github/andrekirst/04_KataFahrplanauskunft))*
* [ ] Der Pull Request-Ersteller behebt die vom Code Reviewer bemängelten Stellen bzw. bespricht diese

**Comment by andrekirst** [comment]
@slempart Ich weise den Issue mal dir zu, damit du auch mal wieder was machen kannst. Ich habe schon ein wenig angefangen, eine rekursive Methode zu bauen.

**Comment by slempart** [comment]
@andrekirst Der VerbindungsauskunftErgebnisTyp ist meiner Meinung nach, nicht ein Attribut der Verbindung. Diese Eigenschaft wird immer anhand einer Liste von Verbindungen berechnet, deren Ergebnis eine Liste von ,sagen wir mal, Verbindungsauskunft hat. Eine Verbindungsauskunft hätte dann die Eigenschaft VerbindungsauskunftErgebnisTyp.

**Comment by andrekirst** [comment]
Ganz zu Ende gedacht ist es von mir noch nicht. Ich wollte halt was einbauen, um herauszufinden, welche Route die schnellste, mit den wenigsten Umstiegen, etc. ist.
