### ISSUE TITLE
Fehler bei der Konvertierung der Zeit von Zahl zu Text, wenn die Zahl den Wert 800 hat

### ISSUE THREAD

**Issue by andrekirst** [andrekirst/04_KataFahrplanauskunft#98]
# Beschreibung

Es wird eine falsche Uhrzeit als Text ausgegeben, wenn die Zahl den Wert 800 hat. Es kommt derzeit **01:20** raus. Raus kommen sollte aber **13:20**. Betroffen ist die Klasse `Funktionen/ZeitKonverter`

## Betroffene Komponenten

* [x] Fahrplanauskunft
* [x] Fahrplanauskunft.Test

## Dokumentationsanpassungen

* [x] Testfall-Dokumentation
* [x] Release-Notes

## Testfälle

* [x] **Fahrplanauskunft.Test**
    * [x] *ZuUhrzeitText_Ganzzahl_800_Text_1320* - Es soll die Funktion *ZuUhrzeitText* mit dem Wert **800** aufgerufen werden und die Ausgabe soll "13:20" betragen.
    * [x] *ZuUhrzeitZahl_Text_1320_Ganzzahl_800* - Es soll die Funktion *ZuUhrzeitZahl* mit dem Wert **13:20** aufgerufen werden und die Ausgabe soll 800 betragen.

## Ablauf beim Entwickeln und Code Review

* [x] Branch erstellt
* [x] Dem Issue das Label `branch erstellt` vergeben
* [x] Entwicklungsarbeit
* [x] Pull Request erstellt
* [x] Dem Issue das Label `pr erstellt` vergeben
* [x] Der Pull Request-Ersteller behebt die von StyleCop und anderen Analyzern entstandenen Einträge
* [x] Der Pull Request-Ersteller behebt in der Entwicklung entstandene SonarQube-Einträge (Bugs, Vulnerabilities, Code Smells, Coverage, Duplications) *([https://sonarqube.com/dashboard/index/04_KataFahrplanauskunft](https://sonarqube.com/dashboard/index/04_KataFahrplanauskunft))*
* [x] Der Pull Request-Ersteller behebt in der Entwicklung entstandene Coveralls.io-Einträge (Code Coverage) *([https://coveralls.io/github/andrekirst/04_KataFahrplanauskunft](https://coveralls.io/github/andrekirst/04_KataFahrplanauskunft))*
* [x] Der Pull Request-Ersteller behebt die vom Code Reviewer bemängelten Stellen bzw. bespricht diese

**Comment by andrekirst** [comment]
@slempart Ich nehme mir den Issue doch an mich.

**Comment by slempart** [comment]
Einfach weggenommen

**Comment by andrekirst** [comment]
@slempart Willst du es doch machen?

**Comment by andrekirst** [comment]
Da hast du ihn wieder

**Comment by slempart** [comment]
Danke

**Comment by andrekirst** [comment]
Mit PR #99 umgesetzt. Kann geschlossen werden.
